### ISSUE TITLE
main() will exit even if the event queue is not empty

### ISSUE THREAD

**Issue by casret** [sehrope/node-async-main#2]
This bit me today.  If we hit the end of the main function, even if there are events to be run, it will just exit, because of the process.exit.  This is a problem if you are waiting for something you can't await (like a setTimeout, or in my case websockets.)

Trivial repro case:

```
const main = require('async-main').default;
main(async () => {
  setTimeout(() => console.log("I will never get reached."), 100)
})
```

**Comment by sehrope** [comment]
That behavior is intentional so that background events that are not part of the `main()` application flow do not prevent the process from exiting. For example if you create a DB connection via a pool, the node process will not exit until you shutdown the pool and close all outstanding connections or the pool expires the connection.

If you want a task to be part of the main flow then you need to make sure that something is waiting for its completion. A handy trick for converting an arbitrary asynchronous operation to be usable via async/await is via manual Promise creation. In your example it'd be something like:

```js
main(async () => {
    await new Promise((resolve) => {
        setTimeout(() => {
            console.log("I will be logged before exit")
            resolve()
        }, 100)
    })
})
```

Lookup "*converting callbacks to Promises*" for more complicated examples.

Note that this module is not meant to be used to start long running processes like a web server. The target use case is things like scripting where you have a series of potentially async tasks that you want completed.

**Comment by casret** [comment]
In the websocket client case, it's not so easy to convert to promises, but it sounds like that isn't the target case.  I suggest adding a little documentation around the Process.exit behavior upon the main completion.  Something like the first line in your comment would be great.
